[workspace]
resolver = "3"
members = ["mmwinnow", "mmtorust", "openmodelica", "openmodelica_util", "metamodelica", "openmodelica_frontend", "openmodelica_backend", "openmodelica_susan", "openmodelica_nf_frontend", "openmodelica_util_datatypes_basic", "openmodelica_ast", "openmodelica_frontend_types", "openmodelica_frontend_dump"]
[workspace.dependencies]
anyhow = "1.0.102"
arcstr = "1.2.0"
list_comprehension_macro = "0.1.1"
const-str = "1.1.0"
rayon = "1"
winnow = "0.7"
loop_unwrap = "0.2.0"
tailcall = "2.3.0"
match_deref = "0.1.2"
ordered-float = "5.3.0"
num-traits = "0.2.19"
mmtorust = {path = "mmtorust"}
mmwinnow = {path = "mmwinnow"}
metamodelica = {path = "metamodelica"}
openmodelica_ast = {path = "openmodelica_ast"}
openmodelica_frontend = {path = "openmodelica_frontend"}
openmodelica_frontend_types = {path = "openmodelica_frontend_types"}
openmodelica_frontend_dump = {path = "openmodelica_frontend_dump"}
openmodelica_nf_frontend = {path = "openmodelica_nf_frontend"}
openmodelica_util = {path = "openmodelica_util"}
openmodelica_backend = {path = "openmodelica_backend"}
openmodelica_susan = {path = "openmodelica_susan"}
openmodelica_util_datatypes_basic = {path = "openmodelica_util_datatypes_basic"}

#[profile.release]
#debug = true
#strip = false
