// Hand-maintained: NOT generated by mmtorust.
//
// Rust port of `OMCompiler/Compiler/Util/SimulationResults.mo`, whose bodies
// are all `external "C"` wrappers over
// `OMCompiler/Compiler/runtime/SimulationResults.c` (a result-file reader for
// .mat-v4 / .plt / .csv with a process-global cache, `simresglob`) and
// `SimulationResultsCmp.c` / `SimulationResultsCmpTubes.c` (result
// comparison). mmtorust can only emit `todo!()` for `external "C"` bodies,
// so this module is hand-written and `SimulationResults` is listed in
// `HANDWRITTEN_TOP_PACKAGES` (mmtorust/src/codegen.rs) to skip its codegen.
//
// Current state: only [`close`] is implemented (the per-process reader cache
// does not exist yet, so releasing it is a no-op — but `simulate()` calls it
// unconditionally before each run and must not fail). The readers and
// comparison functions stay as explicit `todo!()`s until something exercises
// them; whoever implements them first needs a .mat-4 reader equivalent to
// `SimulationRuntime/c/util/read_matlab4.c`, plus the per-process cache that
// `close` must then clear.

/*
 * This file is part of OpenModelica.
 *
 * Copyright (c) 1998-2026, Open Source Modelica Consortium (OSMC),
 * c/o Linköpings universitet, Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF AGPL VERSION 3 LICENSE OR
 * THIS OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.8.
 * ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
 * RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GNU AGPL
 * VERSION 3, ACCORDING TO RECIPIENTS CHOICE.
 *
 * See the full OSMC Public License conditions for more details.
 *
 */
#![allow(non_snake_case, unused_variables, unused_mut, dead_code)]

use std::sync::Arc;

use anyhow::Result;
use arcstr::ArcStr;

use openmodelica_frontend_types::Values;

pub fn val(mut filename: ArcStr, mut varname: ArcStr, mut timeStamp: metamodelica::Real) -> Result<metamodelica::Real> {
    // C: SimulationResults_val — read one variable's value at a given time
    // (with linear interpolation between sample points) from the cached
    // result file.
    todo!("SimulationResults.val: result-file reader not yet ported")
}

pub fn readVariables(mut filename: ArcStr, mut readParameters: bool, mut openmodelicaStyle: bool) -> Result<Arc<metamodelica::List<ArcStr>>> {
    // C: SimulationResults_readVariables — list the variable names stored in
    // a result file.
    todo!("SimulationResults.readVariables: result-file reader not yet ported")
}

pub fn readDataset(mut filename: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>, mut dimsize: i32) -> Result<Arc<Values::Value>> {
    // C: SimulationResults_readDataset — read the full trajectories of the
    // given variables as a matrix. The MM wrapper converts the resulting
    // list<list<Real>> into Values.ARRAY rows via ValuesMake.makeReal /
    // makeArray; reimplement that conversion when porting (see the generated
    // readDataset/readDataset_work pair in this file's git history).
    todo!("SimulationResults.readDataset: result-file reader not yet ported")
}

pub fn readSimulationResultSize(mut filename: ArcStr) -> Result<i32> {
    // C: SimulationResults_readSimulationResultSize — number of sample
    // points in a result file.
    todo!("SimulationResults.readSimulationResultSize: result-file reader not yet ported")
}

pub fn close() -> () {
    // C: SimulationResultsImpl__close(&simresglob) — drop the process-global
    // cached result-file handle so the next read (possibly of a re-run
    // simulation's fresh file) reopens it, and so the OS file handle is
    // released between `simulate()` calls. This port has no reader cache
    // yet (see the module-level comment), so there is nothing to release;
    // when a cache is added for `val`/`readDataset`, it MUST be cleared
    // here.
}

pub fn cmpSimulationResults(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut logfilename: ArcStr, mut refTol: metamodelica::Real, mut absTol: metamodelica::Real, mut vars: Arc<metamodelica::List<ArcStr>>) -> Result<Arc<metamodelica::List<ArcStr>>> {
    // C: SimulationResults_cmpSimulationResults (SimulationResultsCmp.c).
    todo!("SimulationResults.cmpSimulationResults: result comparison not yet ported")
}

pub fn deltaSimulationResults(mut filename: ArcStr, mut reffilename: ArcStr, mut method: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>) -> Result<metamodelica::Real> {
    // C: SimulationResults_deltaSimulationResults (SimulationResultsCmp.c).
    todo!("SimulationResults.deltaSimulationResults: result comparison not yet ported")
}

pub fn diffSimulationResults(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut prefix: ArcStr, mut refTol: metamodelica::Real, mut relTolDiffMaxMin: metamodelica::Real, mut rangeDelta: metamodelica::Real, mut vars: Arc<metamodelica::List<ArcStr>>, mut keepEqualResults: bool) -> Result<(bool, Arc<metamodelica::List<ArcStr>>)> {
    // C: SimulationResults_diffSimulationResults (SimulationResultsCmpTubes.c).
    todo!("SimulationResults.diffSimulationResults: result comparison not yet ported")
}

pub fn diffSimulationResultsHtml(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut refTol: metamodelica::Real, mut relTolDiffMaxMin: metamodelica::Real, mut rangeDelta: metamodelica::Real, mut var: ArcStr) -> Result<ArcStr> {
    // C: SimulationResults_diffSimulationResultsHtml (SimulationResultsCmpTubes.c).
    todo!("SimulationResults.diffSimulationResultsHtml: result comparison not yet ported")
}

pub fn filterSimulationResults(mut inFile: ArcStr, mut outFile: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>, mut numberOfIntervals: i32, mut removeDescription: bool, mut hintReadAllVars: bool) -> Result<bool> {
    // C: SimulationResults_filterSimulationResults — copy a result file
    // keeping only the requested variables / intervals.
    todo!("SimulationResults.filterSimulationResults: result filtering not yet ported")
}
