// Hand-maintained: NOT generated by mmtorust.
//
// Rust port of `OMCompiler/Compiler/Util/SimulationResults.mo`, whose bodies
// are all `external "C"` wrappers over
// `OMCompiler/Compiler/runtime/SimulationResults.c` (a result-file reader for
// .mat-v4 / .plt / .csv with a process-global cache, `simresglob`) and
// `SimulationResultsCmp.c` / `SimulationResultsCmpTubes.c` (result
// comparison). mmtorust can only emit `todo!()` for `external "C"` bodies,
// so this module is hand-written and `SimulationResults` is listed in
// `HANDWRITTEN_TOP_PACKAGES` (mmtorust/src/codegen.rs) to skip its codegen.
//
// Current state: only [`close`] is implemented (the per-process reader cache
// does not exist yet, so releasing it is a no-op — but `simulate()` calls it
// unconditionally before each run and must not fail). The readers and
// comparison functions stay as explicit `todo!()`s until something exercises
// them; whoever implements them first needs a .mat-4 reader equivalent to
// `SimulationRuntime/c/util/read_matlab4.c`, plus the per-process cache that
// `close` must then clear.

/*
 * This file is part of OpenModelica.
 *
 * Copyright (c) 1998-2026, Open Source Modelica Consortium (OSMC),
 * c/o Linköpings universitet, Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF AGPL VERSION 3 LICENSE OR
 * THIS OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.8.
 * ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
 * RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GNU AGPL
 * VERSION 3, ACCORDING TO RECIPIENTS CHOICE.
 *
 * See the full OSMC Public License conditions for more details.
 *
 */
#![allow(non_snake_case, unused_variables, unused_mut, dead_code)]

use std::sync::{Arc, Mutex, MutexGuard};
use std::time::SystemTime;

use anyhow::{bail, Result};
use arcstr::{literal, ArcStr};

use metamodelica::{List, OrderedFloat};
use openmodelica_frontend_types::Values;
use openmodelica_util::{Error, ErrorTypes, Gettext};

// The MATLAB v4 reader lives in a sibling file. lib.rs is regenerated by
// mmtorust and only declares the top-level packages, so the submodule is
// attached here instead.
#[path = "read_matlab4.rs"]
mod read_matlab4;
use read_matlab4::MatReader;

// Scripting error messages, mirroring the inline `c_add_message(NULL, -1, ...)`
// calls in the C `SimulationResults.c`. Tokens are supplied in the order the
// `%s` placeholders appear in the format string.
static ERROR_UNKNOWN_SUFFIX: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Unknown result-file suffix of file '%s'") },
};
static ERROR_OPEN_FAILED: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Failed to open simulation result %s: %s") },
};
static ERROR_VAR_NOT_FOUND: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("%s not found in %s\n") },
};
static ERROR_VAL_NOT_DEFINED: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("%s not defined at time %s (startTime=%s, stopTime=%s).") },
};
static ERROR_DIMSIZE_MISMATCH: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("readDataset(...): Expected and actual dimension sizes do not match.") },
};
static ERROR_COULD_NOT_READ_VAR: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Could not read variable %s in file %s.") },
};

/// The process-global reader cache mirroring the C `simresglob` "super cache":
/// repeated `val()`/`readDataset()` calls on the same unchanged file reuse the
/// parsed reader. Guarded by a `Mutex` for thread safety. These functions run
/// at script level (CevalScript), never on a compiler hot path, so taking the
/// lock across the file read is fine. [`close`] clears it.
struct CachedReader {
    fileName: ArcStr,
    mtime: Option<SystemTime>,
    reader: MatReader,
}
static READER_CACHE: Mutex<Option<CachedReader>> = Mutex::new(None);

fn err(msg: &ErrorTypes::Message, tokens: impl IntoIterator<Item = ArcStr>) -> Result<()> {
    Error::addMessage(msg.clone(), Arc::new(List::from_iter(tokens)))
}

/// Lock the cache and ensure it holds an open reader for `filename`, reopening
/// when the path or mtime changed. Returns `None` (after emitting a scripting
/// error) for unsupported suffixes or open failures. Only MATLAB v4 (`.mat`)
/// is ported; `.plt`/`.csv` readers from the C runtime are not.
fn lock_reader(filename: &ArcStr) -> Result<Option<MutexGuard<'static, Option<CachedReader>>>> {
    if !filename.ends_with(".mat") {
        err(&ERROR_UNKNOWN_SUFFIX, [filename.clone()])?;
        return Ok(None);
    }
    let mtime = std::fs::metadata(filename.as_str())
        .ok()
        .and_then(|m| m.modified().ok());
    let mut guard = READER_CACHE.lock().unwrap();
    let reuse = matches!(&*guard, Some(c)
        if c.fileName == *filename && mtime.is_some() && c.mtime == mtime);
    if !reuse {
        match MatReader::open(filename.as_str()) {
            Ok(reader) => {
                *guard = Some(CachedReader { fileName: filename.clone(), mtime, reader });
            }
            Err(e) => {
                *guard = None;
                err(&ERROR_OPEN_FAILED, [filename.clone(), ArcStr::from(e)])?;
                return Ok(None);
            }
        }
    }
    Ok(Some(guard))
}

/// Build a `Values.REAL`.
fn mk_real(x: f64) -> Arc<Values::Value> {
    Arc::new(Values::REAL { real: OrderedFloat(x) })
}

/// Wrap a row of `Values` in a `Values.ARRAY`, mirroring `ValuesMake.makeArray`:
/// the new outer dimension is prepended to the inner array's `dimLst`.
fn make_array(vals: Vec<Arc<Values::Value>>) -> Arc<Values::Value> {
    let n = vals.len() as i32;
    let inner_dims: Arc<List<i32>> = match vals.first().map(|v| &**v) {
        Some(Values::ARRAY { dimLst, .. }) => dimLst.clone(),
        _ => Arc::new(List::Nil),
    };
    Arc::new(Values::ARRAY {
        valueLst: Arc::new(List::from_iter(vals)),
        dimLst: metamodelica::cons(n, inner_dims),
    })
}

pub fn val(mut filename: ArcStr, mut varname: ArcStr, mut timeStamp: metamodelica::Real) -> Result<metamodelica::Real> {
    // C: SimulationResults_val — read one variable's value at a given time
    // (with linear interpolation between sample points) from the cached
    // result file. On any error the C code emits a scripting message and
    // returns NaN; the script continues.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => return Ok(OrderedFloat(f64::NAN)),
    };
    let reader = &mut guard.as_mut().unwrap().reader;
    let var = match reader.find_var(varname.as_str()) {
        Some(v) => v,
        None => {
            drop(guard);
            err(&ERROR_VAR_NOT_FOUND, [varname.clone(), filename.clone()])?;
            return Ok(OrderedFloat(f64::NAN));
        }
    };
    let t = timeStamp.into_inner();
    match reader.val(var, t) {
        Some(v) => Ok(OrderedFloat(v)),
        None => {
            let start = reader.start_time();
            let stop = reader.stop_time();
            drop(guard);
            err(
                &ERROR_VAL_NOT_DEFINED,
                [
                    varname.clone(),
                    ArcStr::from(format_g(t)),
                    ArcStr::from(format_g(start)),
                    ArcStr::from(format_g(stop)),
                ],
            )?;
            Ok(OrderedFloat(f64::NAN))
        }
    }
}

pub fn readVariables(mut filename: ArcStr, mut readParameters: bool, mut openmodelicaStyle: bool) -> Result<Arc<metamodelica::List<ArcStr>>> {
    // C: SimulationResults_readVariables — list the variable names stored in
    // a result file (sorted), optionally including parameters and converting
    // der()-style names to OpenModelica style.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => return Ok(Arc::new(List::Nil)),
    };
    let reader = &mut guard.as_mut().unwrap().reader;
    let mut names: Vec<ArcStr> = Vec::new();
    for info in &reader.allInfo {
        if readParameters || !info.isParam {
            let name = if openmodelicaStyle {
                let converted = read_matlab4::openmodelica_style_name(&info.name)
                    .unwrap_or_else(|| info.name.clone());
                ArcStr::from(converted.replace(' ', ""))
            } else {
                ArcStr::from(info.name.as_str())
            };
            names.push(name);
        }
    }
    Ok(Arc::new(List::from_iter(names)))
}

pub fn readDataset(mut filename: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>, mut dimsize: i32) -> Result<Arc<Values::Value>> {
    // C: SimulationResults_readDataset — read the full trajectories of the
    // given variables, returning a Values.ARRAY matrix (variable-major rows,
    // time-major columns). This combines the external `readDataset_work`
    // result with the `ValuesMake.makeReal`/`makeArray` conversion the MM
    // `readDataset` wrapper performed.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => bail!("readDataset: could not open {filename}"),
    };
    let reader = &mut guard.as_mut().unwrap().reader;
    let mut dim = dimsize;
    if dim == 0 {
        dim = reader.nrows as i32;
    } else if reader.nrows as i32 != dim {
        drop(guard);
        err(&ERROR_DIMSIZE_MISMATCH, [])?;
        bail!("readDataset: dimension size mismatch for {filename}");
    }
    let dim = dim as usize;
    let mut rows: Vec<Arc<Values::Value>> = Vec::new();
    for var in vars.as_ref() {
        let idx = match reader.find_var(var.as_str()) {
            Some(i) => i,
            None => {
                drop(guard);
                err(&ERROR_COULD_NOT_READ_VAR, [var.clone(), filename.clone()])?;
                bail!("readDataset: variable {var} not found in {filename}");
            }
        };
        let info = &reader.allInfo[idx];
        let isParam = info.isParam;
        let index = info.index;
        let col: Vec<Arc<Values::Value>> = if isParam {
            let p = reader.params[(index.unsigned_abs() as usize) - 1];
            let p = if index < 0 { -p } else { p };
            (0..dim).map(|_| mk_real(p)).collect()
        } else {
            let vals = match reader.read_vals(index) {
                Some(v) => v,
                None => {
                    drop(guard);
                    err(&ERROR_COULD_NOT_READ_VAR, [var.clone(), filename.clone()])?;
                    bail!("readDataset: could not read variable {var} in {filename}");
                }
            };
            (0..dim).map(|i| mk_real(vals[i])).collect()
        };
        rows.push(make_array(col));
    }
    Ok(make_array(rows))
}

pub fn readSimulationResultSize(mut filename: ArcStr) -> Result<i32> {
    // C: SimulationResults_readSimulationResultSize — number of sample
    // points (rows) in a result file; -1 if it cannot be opened.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => return Ok(-1),
    };
    Ok(guard.as_ref().unwrap().reader.nrows as i32)
}

pub fn close() -> () {
    // C: SimulationResultsImpl__close(&simresglob) — drop the process-global
    // cached result-file handle so the next read (possibly of a re-run
    // simulation's fresh file) reopens it, and so the OS file handle is
    // released between `simulate()` calls.
    *READER_CACHE.lock().unwrap() = None;
}

/// Format a double the way C's `%g` does, for error-message interpolation.
fn format_g(x: f64) -> String {
    // Rust has no direct `%g`; this matches the common cases (finite values use
    // the shortest round-tripping representation, which is close enough for the
    // diagnostic text). Non-finite values print like C.
    if x.is_nan() {
        "nan".to_string()
    } else if x.is_infinite() {
        if x < 0.0 { "-inf".to_string() } else { "inf".to_string() }
    } else {
        format!("{x}")
    }
}

pub fn cmpSimulationResults(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut logfilename: ArcStr, mut refTol: metamodelica::Real, mut absTol: metamodelica::Real, mut vars: Arc<metamodelica::List<ArcStr>>) -> Result<Arc<metamodelica::List<ArcStr>>> {
    // C: SimulationResults_cmpSimulationResults (SimulationResultsCmp.c).
    todo!("SimulationResults.cmpSimulationResults: result comparison not yet ported")
}

pub fn deltaSimulationResults(mut filename: ArcStr, mut reffilename: ArcStr, mut method: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>) -> Result<metamodelica::Real> {
    // C: SimulationResults_deltaSimulationResults (SimulationResultsCmp.c).
    todo!("SimulationResults.deltaSimulationResults: result comparison not yet ported")
}

pub fn diffSimulationResults(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut prefix: ArcStr, mut refTol: metamodelica::Real, mut relTolDiffMaxMin: metamodelica::Real, mut rangeDelta: metamodelica::Real, mut vars: Arc<metamodelica::List<ArcStr>>, mut keepEqualResults: bool) -> Result<(bool, Arc<metamodelica::List<ArcStr>>)> {
    // C: SimulationResults_diffSimulationResults (SimulationResultsCmpTubes.c).
    todo!("SimulationResults.diffSimulationResults: result comparison not yet ported")
}

pub fn diffSimulationResultsHtml(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut refTol: metamodelica::Real, mut relTolDiffMaxMin: metamodelica::Real, mut rangeDelta: metamodelica::Real, mut var: ArcStr) -> Result<ArcStr> {
    // C: SimulationResults_diffSimulationResultsHtml (SimulationResultsCmpTubes.c).
    todo!("SimulationResults.diffSimulationResultsHtml: result comparison not yet ported")
}

pub fn filterSimulationResults(mut inFile: ArcStr, mut outFile: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>, mut numberOfIntervals: i32, mut removeDescription: bool, mut hintReadAllVars: bool) -> Result<bool> {
    // C: SimulationResults_filterSimulationResults — copy a result file
    // keeping only the requested variables / intervals.
    todo!("SimulationResults.filterSimulationResults: result filtering not yet ported")
}
