// Hand-maintained: NOT generated by mmtorust.
//
// Rust port of `OMCompiler/Compiler/Util/SimulationResults.mo`, whose bodies
// are all `external "C"` wrappers over
// `OMCompiler/Compiler/runtime/SimulationResults.c` (a result-file reader for
// .mat-v4 / .plt / .csv with a process-global cache, `simresglob`) and
// `SimulationResultsCmp.c` / `SimulationResultsCmpTubes.c` (result
// comparison). mmtorust can only emit `todo!()` for `external "C"` bodies,
// so this module is hand-written and `SimulationResults` is listed in
// `HANDWRITTEN_TOP_PACKAGES` (mmtorust/src/codegen.rs) to skip its codegen.
//
// Current state: only [`close`] is implemented (the per-process reader cache
// does not exist yet, so releasing it is a no-op — but `simulate()` calls it
// unconditionally before each run and must not fail). The readers and
// comparison functions stay as explicit `todo!()`s until something exercises
// them; whoever implements them first needs a .mat-4 reader equivalent to
// `SimulationRuntime/c/util/read_matlab4.c`, plus the per-process cache that
// `close` must then clear.

/*
 * This file is part of OpenModelica.
 *
 * Copyright (c) 1998-2026, Open Source Modelica Consortium (OSMC),
 * c/o Linköpings universitet, Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF AGPL VERSION 3 LICENSE OR
 * THIS OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.8.
 * ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
 * RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GNU AGPL
 * VERSION 3, ACCORDING TO RECIPIENTS CHOICE.
 *
 * See the full OSMC Public License conditions for more details.
 *
 */
#![allow(non_snake_case, unused_variables, unused_mut, dead_code)]

use std::sync::{Arc, Mutex, MutexGuard};
use std::time::SystemTime;

use anyhow::{bail, Result};
use arcstr::{literal, ArcStr};

use metamodelica::{List, OrderedFloat};
use openmodelica_frontend_types::Values;
use openmodelica_util::{Error, ErrorTypes, Gettext};

// The MATLAB v4 reader lives in a sibling file. lib.rs is regenerated by
// mmtorust and only declares the top-level packages, so the submodule is
// attached here instead.
#[path = "read_matlab4.rs"]
mod read_matlab4;
use read_matlab4::MatReader;

// Scripting error messages, mirroring the inline `c_add_message(NULL, -1, ...)`
// calls in the C `SimulationResults.c`. Tokens are supplied in the order the
// `%s` placeholders appear in the format string.
static ERROR_UNKNOWN_SUFFIX: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Unknown result-file suffix of file '%s'") },
};
static ERROR_OPEN_FAILED: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Failed to open simulation result %s: %s") },
};
static ERROR_VAR_NOT_FOUND: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("%s not found in %s\n") },
};
static ERROR_VAL_NOT_DEFINED: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("%s not defined at time %s (startTime=%s, stopTime=%s).") },
};
static ERROR_DIMSIZE_MISMATCH: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("readDataset(...): Expected and actual dimension sizes do not match.") },
};
static ERROR_COULD_NOT_READ_VAR: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Could not read variable %s in file %s.") },
};
// Result-comparison messages, mirroring SimulationResultsCmp.c.
static ERROR_OPEN_FILE: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Error opening file: %s") },
};
static ERROR_OPEN_REFFILE: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Error opening reference file: %s") },
};
static ERROR_GET_VARS: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Error getting variables") },
};
static ERROR_GET_TIME: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Error getting time") },
};
static ERROR_GET_TIME_REF: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Error getting time from reference file") },
};
// NB: the token order mirrors the C call (msg[0]=file, msg[1]=var), which the C
// code passes in that order even though the format reads "variable %s ... file %s".
static ERROR_GET_DATA_FAILED: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::WARNING,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("Get data of variable %s from file %s failed!\n") },
};
static ERROR_FILE_STARTS_BEFORE: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("The result file starts before the reference file.") },
};
static ERROR_FILE_ENDS_BEFORE: ErrorTypes::Message = ErrorTypes::Message {
    id: -1,
    ty: ErrorTypes::MessageType::SCRIPTING,
    severity: ErrorTypes::Severity::ERROR,
    message: Gettext::TranslatableContent::gettext { msgid: literal!("The result file ends before the reference file.") },
};

/// The process-global reader cache mirroring the C `simresglob` "super cache":
/// repeated `val()`/`readDataset()` calls on the same unchanged file reuse the
/// parsed reader. Guarded by a `Mutex` for thread safety. These functions run
/// at script level (CevalScript), never on a compiler hot path, so taking the
/// lock across the file read is fine. [`close`] clears it.
struct CachedReader {
    fileName: ArcStr,
    mtime: Option<SystemTime>,
    reader: MatReader,
}
static READER_CACHE: Mutex<Option<CachedReader>> = Mutex::new(None);

fn err(msg: &ErrorTypes::Message, tokens: impl IntoIterator<Item = ArcStr>) -> Result<()> {
    Error::addMessage(msg.clone(), Arc::new(List::from_iter(tokens)))
}

/// Lock the cache and ensure it holds an open reader for `filename`, reopening
/// when the path or mtime changed. Returns `None` (after emitting a scripting
/// error) for unsupported suffixes or open failures. Only MATLAB v4 (`.mat`)
/// is ported; `.plt`/`.csv` readers from the C runtime are not.
fn lock_reader(filename: &ArcStr) -> Result<Option<MutexGuard<'static, Option<CachedReader>>>> {
    if !filename.ends_with(".mat") {
        err(&ERROR_UNKNOWN_SUFFIX, [filename.clone()])?;
        return Ok(None);
    }
    let mtime = std::fs::metadata(filename.as_str())
        .ok()
        .and_then(|m| m.modified().ok());
    let mut guard = READER_CACHE.lock().unwrap();
    let reuse = matches!(&*guard, Some(c)
        if c.fileName == *filename && mtime.is_some() && c.mtime == mtime);
    if !reuse {
        match MatReader::open(filename.as_str()) {
            Ok(reader) => {
                *guard = Some(CachedReader { fileName: filename.clone(), mtime, reader });
            }
            Err(e) => {
                *guard = None;
                err(&ERROR_OPEN_FAILED, [filename.clone(), ArcStr::from(e)])?;
                return Ok(None);
            }
        }
    }
    Ok(Some(guard))
}

/// Build a `Values.REAL`.
fn mk_real(x: f64) -> Arc<Values::Value> {
    Arc::new(Values::REAL { real: OrderedFloat(x) })
}

/// Wrap a row of `Values` in a `Values.ARRAY`, mirroring `ValuesMake.makeArray`:
/// the new outer dimension is prepended to the inner array's `dimLst`.
fn make_array(vals: Vec<Arc<Values::Value>>) -> Arc<Values::Value> {
    let n = vals.len() as i32;
    let inner_dims: Arc<List<i32>> = match vals.first().map(|v| &**v) {
        Some(Values::ARRAY { dimLst, .. }) => dimLst.clone(),
        _ => Arc::new(List::Nil),
    };
    Arc::new(Values::ARRAY {
        valueLst: Arc::new(List::from_iter(vals)),
        dimLst: metamodelica::cons(n, inner_dims),
    })
}

pub fn val(mut filename: ArcStr, mut varname: ArcStr, mut timeStamp: metamodelica::Real) -> Result<metamodelica::Real> {
    // C: SimulationResults_val — read one variable's value at a given time
    // (with linear interpolation between sample points) from the cached
    // result file. On any error the C code emits a scripting message and
    // returns NaN; the script continues.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => return Ok(OrderedFloat(f64::NAN)),
    };
    let reader = &mut guard.as_mut().unwrap().reader;
    let var = match reader.find_var(varname.as_str()) {
        Some(v) => v,
        None => {
            drop(guard);
            err(&ERROR_VAR_NOT_FOUND, [varname.clone(), filename.clone()])?;
            return Ok(OrderedFloat(f64::NAN));
        }
    };
    let t = timeStamp.into_inner();
    match reader.val(var, t) {
        Some(v) => Ok(OrderedFloat(v)),
        None => {
            let start = reader.start_time();
            let stop = reader.stop_time();
            drop(guard);
            err(
                &ERROR_VAL_NOT_DEFINED,
                [
                    varname.clone(),
                    ArcStr::from(format_g(t)),
                    ArcStr::from(format_g(start)),
                    ArcStr::from(format_g(stop)),
                ],
            )?;
            Ok(OrderedFloat(f64::NAN))
        }
    }
}

pub fn readVariables(mut filename: ArcStr, mut readParameters: bool, mut openmodelicaStyle: bool) -> Result<Arc<metamodelica::List<ArcStr>>> {
    // C: SimulationResults_readVariables — list the variable names stored in
    // a result file (sorted), optionally including parameters and converting
    // der()-style names to OpenModelica style.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => return Ok(Arc::new(List::Nil)),
    };
    let reader = &mut guard.as_mut().unwrap().reader;
    let mut names: Vec<ArcStr> = Vec::new();
    for info in &reader.allInfo {
        if readParameters || !info.isParam {
            let name = if openmodelicaStyle {
                let converted = read_matlab4::openmodelica_style_name(&info.name)
                    .unwrap_or_else(|| info.name.clone());
                ArcStr::from(converted.replace(' ', ""))
            } else {
                ArcStr::from(info.name.as_str())
            };
            names.push(name);
        }
    }
    Ok(Arc::new(List::from_iter(names)))
}

pub fn readDataset(mut filename: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>, mut dimsize: i32) -> Result<Arc<Values::Value>> {
    // C: SimulationResults_readDataset — read the full trajectories of the
    // given variables, returning a Values.ARRAY matrix (variable-major rows,
    // time-major columns). This combines the external `readDataset_work`
    // result with the `ValuesMake.makeReal`/`makeArray` conversion the MM
    // `readDataset` wrapper performed.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => bail!("readDataset: could not open {filename}"),
    };
    let reader = &mut guard.as_mut().unwrap().reader;
    let mut dim = dimsize;
    if dim == 0 {
        dim = reader.nrows as i32;
    } else if reader.nrows as i32 != dim {
        drop(guard);
        err(&ERROR_DIMSIZE_MISMATCH, [])?;
        bail!("readDataset: dimension size mismatch for {filename}");
    }
    let dim = dim as usize;
    let mut rows: Vec<Arc<Values::Value>> = Vec::new();
    for var in vars.as_ref() {
        let idx = match reader.find_var(var.as_str()) {
            Some(i) => i,
            None => {
                drop(guard);
                err(&ERROR_COULD_NOT_READ_VAR, [var.clone(), filename.clone()])?;
                bail!("readDataset: variable {var} not found in {filename}");
            }
        };
        let info = &reader.allInfo[idx];
        let isParam = info.isParam;
        let index = info.index;
        let col: Vec<Arc<Values::Value>> = if isParam {
            let p = reader.params[(index.unsigned_abs() as usize) - 1];
            let p = if index < 0 { -p } else { p };
            (0..dim).map(|_| mk_real(p)).collect()
        } else {
            let vals = match reader.read_vals(index) {
                Some(v) => v,
                None => {
                    drop(guard);
                    err(&ERROR_COULD_NOT_READ_VAR, [var.clone(), filename.clone()])?;
                    bail!("readDataset: could not read variable {var} in {filename}");
                }
            };
            (0..dim).map(|i| mk_real(vals[i])).collect()
        };
        rows.push(make_array(col));
    }
    Ok(make_array(rows))
}

pub fn readSimulationResultSize(mut filename: ArcStr) -> Result<i32> {
    // C: SimulationResults_readSimulationResultSize — number of sample
    // points (rows) in a result file; -1 if it cannot be opened.
    let mut guard = match lock_reader(&filename)? {
        Some(g) => g,
        None => return Ok(-1),
    };
    Ok(guard.as_ref().unwrap().reader.nrows as i32)
}

pub fn close() -> () {
    // C: SimulationResultsImpl__close(&simresglob) — drop the process-global
    // cached result-file handle so the next read (possibly of a re-run
    // simulation's fresh file) reopens it, and so the OS file handle is
    // released between `simulate()` calls.
    *READER_CACHE.lock().unwrap() = None;
}

/// Format a double the way C's `%g` does, for error-message interpolation.
fn format_g(x: f64) -> String {
    // Rust has no direct `%g`; this matches the common cases (finite values use
    // the shortest round-tripping representation, which is close enough for the
    // diagnostic text). Non-finite values print like C.
    if x.is_nan() {
        "nan".to_string()
    } else if x.is_infinite() {
        if x < 0.0 { "-inf".to_string() } else { "inf".to_string() }
    } else {
        format!("{x}")
    }
}

// ---------------------------------------------------------------------------
// Result comparison (port of SimulationResultsCmp.c)
//
// `cmpSimulationResults` is the `isResultCmp=1` path of the C
// `SimulationResultsCmp_compareResults`; it uses `cmpData` (event-aware
// point-by-point comparison with reference interpolation). `deltaSimulationResults`
// is `SimulationResultsCmp_deltaResults` (norm of the difference). Both open
// two independent readers (not the shared `READER_CACHE`, which only holds one
// file) since they compare a result file against a reference simultaneously.
// ---------------------------------------------------------------------------

// almostEqualRelativeAndAbs default tolerances (SimulationResultsCmp.c).
const DOUBLEEQUAL_TOTAL: f64 = 0.0000000001;
const DOUBLEEQUAL_REL: f64 = 0.00001;

/// C `almostEqualRelativeAndAbs`.
fn almost_equal_rel_abs(a: f64, b: f64, reltol: f64, abstol: f64) -> bool {
    let diff = (a - b).abs();
    diff <= abstol || diff <= a.abs().max(b.abs()) * reltol
}

/// C `almostEqualWithDefaultTolerance`.
fn almost_equal_default(a: f64, b: f64) -> bool {
    almost_equal_rel_abs(a, b, DOUBLEEQUAL_REL, DOUBLEEQUAL_TOTAL)
}

/// One row of the diff log, mirroring C `DiffData`.
struct DiffData {
    name: ArcStr,
    data: f64,
    dataref: f64,
    time: f64,
    timeref: f64,
    interpolate: bool,
}

/// C `getData`: full trajectory of `varname` over all `nrows` sample points
/// (a constant vector for parameters), or `None` if the variable is missing.
fn get_data(reader: &mut MatReader, varname: &str) -> Option<Vec<f64>> {
    let idx = reader.find_var(varname)?;
    let (is_param, index) = {
        let info = &reader.allInfo[idx];
        (info.isParam, info.index)
    };
    if is_param {
        let absp = index.unsigned_abs() as usize;
        if absp == 0 || absp > reader.params.len() {
            return None;
        }
        let p = reader.params[absp - 1];
        Some(vec![if index < 0 { -p } else { p }; reader.nrows])
    } else {
        reader.read_vals(index)
    }
}

/// C `SimulationResultsImpl__readVarsFilterAliases` (MATLAB4 branch): the names
/// of all real (non-negated-alias) variables and parameters, one per storage
/// index, in `allInfo` order.
fn read_vars_filter_aliases(reader: &MatReader) -> Vec<ArcStr> {
    let mut seen_param = std::collections::HashSet::new();
    let mut seen_var = std::collections::HashSet::new();
    let mut out = Vec::new();
    for info in reader.allInfo.iter().rev() {
        if info.index <= 0 {
            continue; // negated aliases always have a real variable
        }
        let seen = if info.isParam { &mut seen_param } else { &mut seen_var };
        if !seen.insert(info.index) {
            continue;
        }
        out.push(ArcStr::from(info.name.as_str()));
    }
    out.reverse();
    out
}

/// C `getTimeVarName`: `"time"` unless only `"Time"` is present.
fn get_time_var_name(allvars: &[ArcStr]) -> &'static str {
    for v in allvars {
        if v == "time" {
            return "time";
        }
        if v == "Time" {
            return "Time";
        }
    }
    "time"
}

/// Strip `"` from a variable name (C does this into `var1` before lookups).
fn strip_quotes(var: &str) -> ArcStr {
    if var.contains('"') {
        ArcStr::from(var.replace('"', ""))
    } else {
        ArcStr::from(var)
    }
}

/// Count of leading equal timestamps (C `offset`/`offsetRef`): duplicated
/// initial points that get overwritten with the next value before comparing.
fn leading_dup_count(time: &[f64]) -> usize {
    let mut o = 0;
    while o + 1 < time.len() && time[o] == time[o + 1] {
        o += 1;
    }
    o
}

/// C `cmpData` for the `isResultCmp=1` path: compares one variable's trajectory
/// against the reference (event-aware, with reference interpolation), appends
/// differing points to `ddf`, and returns whether the variable differed.
fn cmp_data(
    varname: &ArcStr,
    time: &[f64],
    reftime: &[f64],
    data: &[f64],
    refdata: &[f64],
    reltol: f64,
    abstol: f64,
    ddf: &mut Vec<DiffData>,
) -> bool {
    let reftime_n = reftime.len() as isize;
    let data_n = data.len();
    let time_n = time.len();

    let mut average = 0.0;
    for &x in refdata {
        average += x.abs();
    }
    average /= refdata.len() as f64;
    average = reltol * average.abs() + abstol;

    let mut isdifferent = false;
    let mut j: isize = 0;
    let mut tr = reftime[0];
    let mut i: usize = 0;
    'outer: while i < data_n {
        let mut t = time[i];
        let d = data[i];
        let mut increased = false;
        while tr < t {
            if j + 1 < reftime_n {
                j += 1;
                tr = reftime[j as usize];
                increased = true;
                if tr == t {
                    break;
                }
            } else {
                break;
            }
        }
        if increased
            && (((t - tr) / tr).abs() > reltol
                || (t - tr).abs() > (t - reftime[(j - 1) as usize]).abs())
        {
            j -= 1;
            tr = reftime[j as usize];
        }

        // Events: at a discontinuity (two equal successive times) compare only
        // the left and right values of the event range.
        if i + 1 < time_n && almost_equal_default(t, time[i + 1]) {
            let d_left = d;
            if i + 1 < data_n {
                while almost_equal_default(t, time[i + 1]) {
                    i += 1;
                    if i + 1 >= data_n {
                        break;
                    }
                }
            }
            t = time[i];
            let d_right = data[i];

            // search event in reference forwards
            let mut refevent = false;
            let mut t_event = t + t * reltol * 0.1;
            if i + 1 <= data_n {
                t_event = if t_event > time[i] { time[i] } else { t_event };
            } else {
                t_event = if t_event > time[i + 1] { time[i + 1] } else { t_event };
            }
            let j_event = j;
            let mut dr_left = 0.0;
            while tr < t_event {
                if j + 1 < reftime_n && almost_equal_default(tr, reftime[(j + 1) as usize]) {
                    dr_left = refdata[j as usize];
                    refevent = true;
                    loop {
                        j += 1;
                        if j + 1 >= reftime_n {
                            break;
                        }
                        if !almost_equal_default(tr, reftime[(j + 1) as usize]) {
                            break;
                        }
                    }
                }
                if !refevent {
                    j += 1;
                    if j >= reftime_n {
                        break;
                    }
                    tr = reftime[j as usize];
                } else {
                    tr = reftime[j as usize];
                    break;
                }
            }
            if refevent {
                tr = reftime[j as usize];
                let dr_right = refdata[j as usize];
                if (d_left - dr_left).abs() < average && (d_right - dr_right).abs() < average {
                    i += 1;
                    continue 'outer;
                }
            } else {
                // search event in reference backwards
                j = j_event;
                tr = reftime[j as usize];
                refevent = false;
                t_event = t - t * reltol * 0.1;
                let mut dr_right = 0.0;
                while tr > t_event {
                    if j > 1 && almost_equal_default(tr, reftime[(j - 1) as usize]) {
                        dr_right = refdata[j as usize];
                        refevent = true;
                        loop {
                            j -= 1;
                            if j <= 1 {
                                break;
                            }
                            if !almost_equal_default(tr, reftime[(j - 1) as usize]) {
                                break;
                            }
                        }
                    }
                    if !refevent {
                        j -= 1;
                        if j == 0 {
                            break;
                        }
                        tr = reftime[j as usize];
                    } else {
                        tr = reftime[j as usize];
                        break;
                    }
                }
                if refevent {
                    tr = reftime[j as usize];
                    dr_left = refdata[j as usize];
                    if (d_left - dr_left).abs() < average && (d_right - dr_right).abs() < average {
                        j = j_event;
                        tr = reftime[j as usize];
                        i += 1;
                        continue 'outer;
                    }
                }
                j = j_event;
                tr = reftime[j as usize];
            }
        }

        // Interpolate the reference to the result time when they don't coincide.
        let interpolate = (t - tr).abs() > 0.00001;
        let mut dr = refdata[j as usize];
        if interpolate {
            if tr > t {
                let mut jj = j;
                if j > 1 {
                    jj = j - 1;
                    if reftime[jj as usize] == tr {
                        loop {
                            jj -= 1;
                            if jj <= 0 {
                                break;
                            }
                            if reftime[jj as usize] != tr {
                                break;
                            }
                        }
                    }
                }
                if reftime[jj as usize] != tr {
                    dr = refdata[jj as usize]
                        + ((dr - refdata[jj as usize]) / (tr - reftime[jj as usize]))
                            * (t - reftime[jj as usize]);
                }
            } else {
                let mut jj = j;
                if j + 1 < reftime_n {
                    jj = j + 1;
                    if reftime[jj as usize] == tr {
                        loop {
                            jj += 1;
                            if jj >= reftime_n {
                                break;
                            }
                            if reftime[jj as usize] != tr {
                                break;
                            }
                        }
                    }
                }
                if reftime[jj as usize] != tr {
                    dr = dr
                        + ((refdata[jj as usize] - dr) / (reftime[jj as usize] - tr)) * (t - tr);
                }
            }
        }

        let mut err = (d - dr).abs();
        if err > average {
            if j + 1 < reftime_n && reftime[(j + 1) as usize] == tr {
                dr = refdata[(j + 1) as usize];
                err = (d - dr).abs();
            }
            if err < average {
                i += 1;
                continue 'outer;
            }
            isdifferent = true;
            ddf.push(DiffData {
                name: varname.clone(),
                data: d,
                dataref: dr,
                time: t,
                timeref: tr,
                interpolate,
            });
        }
        i += 1;
    }
    isdifferent
}

/// C `%.15g` rendering for the diff log file (delegates to the runtime's
/// printf-compatible float formatter).
fn g15(x: f64) -> String {
    openmodelica_util::System::sprintff(literal!("%.15g"), OrderedFloat(x))
        .map(|s| s.to_string())
        .unwrap_or_else(|_| format!("{x}"))
}

/// C `writeLogFile`: dump the differing data points as a semicolon-separated CSV.
fn write_log_file(
    filename: &str,
    ddf: &[DiffData],
    f: &str,
    reff: &str,
    reltol: f64,
    abstol: f64,
) -> std::io::Result<()> {
    use std::fmt::Write as _;
    let mut s = String::new();
    let _ = writeln!(s, "\"Generated by OpenModelica\";;;;;");
    let _ = writeln!(
        s,
        "\"Compared Files\";;;\"absolute tolerance\";{};relative tolerance;{}",
        g15(abstol),
        g15(reltol)
    );
    let _ = writeln!(s, "\"{f}\";;;;;;");
    let _ = writeln!(s, "\"{reff}\";;;;;;");
    let _ = writeln!(
        s,
        "\"Name\";\"Time\";\"DataPoint\";\"RefTime\";\"RefDataPoint\";\"absolute error\";\"relative error\";interpolate;"
    );
    for dd in ddf {
        let _ = writeln!(
            s,
            "{};{};{};{};{};{};{};{};",
            dd.name,
            g15(dd.time),
            g15(dd.data),
            g15(dd.timeref),
            g15(dd.dataref),
            g15((dd.data - dd.dataref).abs()),
            g15(((dd.data - dd.dataref) / dd.dataref).abs()),
            if dd.interpolate { '1' } else { '0' }
        );
    }
    std::fs::write(filename, s)
}

pub fn cmpSimulationResults(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut logfilename: ArcStr, mut refTol: metamodelica::Real, mut absTol: metamodelica::Real, mut vars: Arc<metamodelica::List<ArcStr>>) -> Result<Arc<metamodelica::List<ArcStr>>> {
    // C: SimulationResults_cmpSimulationResults ->
    //    SimulationResultsCmp_compareResults(isResultCmp=1, isHtml=0).
    let reltol = refTol.into_inner();
    let abstol = absTol.into_inner();

    let mut reader_c = match MatReader::open(filename.as_str()) {
        Ok(r) => r,
        Err(_) => {
            err(&ERROR_OPEN_FILE, [filename.clone()])?;
            return Ok(Arc::new(List::Nil));
        }
    };
    let mut reader_ref = match MatReader::open(reffilename.as_str()) {
        Ok(r) => r,
        Err(_) => {
            err(&ERROR_OPEN_REFFILE, [reffilename.clone()])?;
            return Ok(Arc::new(List::Nil));
        }
    };

    let allvars = read_vars_filter_aliases(&reader_c);
    let allvarsref = read_vars_filter_aliases(&reader_ref);

    // Compare-list: the supplied vars, or every reference variable when empty.
    let mut cmpvars: Vec<ArcStr> = vars.as_ref().into_iter().cloned().collect();
    if cmpvars.is_empty() {
        cmpvars = allvarsref.clone();
        if cmpvars.is_empty() {
            err(&ERROR_GET_VARS, [])?;
            return Ok(Arc::new(List::Nil));
        }
    }

    let time_name = get_time_var_name(&allvars);
    let timeref_name = get_time_var_name(&allvarsref);
    let time = match get_data(&mut reader_c, time_name) {
        Some(t) if !t.is_empty() => t,
        _ => {
            err(&ERROR_GET_TIME, [])?;
            return Ok(Arc::new(List::Nil));
        }
    };
    let timeref = match get_data(&mut reader_ref, timeref_name) {
        Some(t) if !t.is_empty() => t,
        _ => {
            err(&ERROR_GET_TIME_REF, [])?;
            return Ok(Arc::new(List::Nil));
        }
    };

    // Warn (but continue) when the end times differ by more than the tolerance.
    let last = *time.last().unwrap();
    let last_ref = *timeref.last().unwrap();
    if (last - last_ref).abs() > reltol * last_ref.abs() {
        let buf = format!(
            "Resultfile and Reference have different end time points!\nReffile[{}]={}\nFile[{}]={}\n",
            timeref.len(),
            format_g(last_ref),
            time.len(),
            format_g(last)
        );
        Error::addMessage(
            ErrorTypes::Message {
                id: -1,
                ty: ErrorTypes::MessageType::SCRIPTING,
                severity: ErrorTypes::Severity::WARNING,
                message: Gettext::TranslatableContent::notrans { r#str: ArcStr::from(buf) },
            },
            Arc::new(List::Nil),
        )?;
    }

    let offset = leading_dup_count(&time);
    let offset_ref = leading_dup_count(&timeref);

    let mut ddf: Vec<DiffData> = Vec::new();
    let mut diff_vars: Vec<ArcStr> = Vec::new();
    let mut nfailed = 0u32;
    for var in &cmpvars {
        let var1 = strip_quotes(var.as_str());
        let mut dataref = match get_data(&mut reader_ref, var1.as_str()) {
            Some(d) if !d.is_empty() => d,
            _ => {
                let file = if runningTestsuite { openmodelica_util::System::basename(reffilename.clone()) } else { reffilename.clone() };
                err(&ERROR_GET_DATA_FAILED, [file, var.clone()])?;
                nfailed += 1;
                continue;
            }
        };
        let mut data = match get_data(&mut reader_c, var1.as_str()) {
            Some(d) if !d.is_empty() => d,
            _ => {
                let file = if runningTestsuite { openmodelica_util::System::basename(filename.clone()) } else { filename.clone() };
                err(&ERROR_GET_DATA_FAILED, [file, var.clone()])?;
                nfailed += 1;
                continue;
            }
        };
        // Adjust the duplicated initial data points (C shifts data[offset..0]).
        for j in (1..=offset).rev() {
            data[j - 1] = data[j];
        }
        for j in (1..=offset_ref).rev() {
            dataref[j - 1] = dataref[j];
        }
        if cmp_data(var, &time, &timeref, &data, &dataref, reltol, abstol, &mut ddf) {
            diff_vars.push(var.clone());
        }
    }

    if let Err(e) = write_log_file(logfilename.as_str(), &ddf, filename.as_str(), reffilename.as_str(), reltol, abstol) {
        let _ = e;
        Error::addMessage(
            ErrorTypes::Message {
                id: -1,
                ty: ErrorTypes::MessageType::SCRIPTING,
                severity: ErrorTypes::Severity::WARNING,
                message: Gettext::TranslatableContent::gettext { msgid: literal!("Cannot write to the difference (.csv) file!\n") },
            },
            Arc::new(List::Nil),
        )?;
    }

    if !ddf.is_empty() || nfailed > 0 || !diff_vars.is_empty() {
        Error::addMessage(
            ErrorTypes::Message {
                id: -1,
                ty: ErrorTypes::MessageType::SCRIPTING,
                severity: ErrorTypes::Severity::WARNING,
                message: Gettext::TranslatableContent::gettext { msgid: literal!("Files not Equal\n") },
            },
            Arc::new(List::Nil),
        )?;
        let mut items = vec![literal!("Files not Equal!")];
        items.extend(diff_vars.into_iter().rev());
        Ok(Arc::new(List::from_iter(items)))
    } else {
        Ok(Arc::new(List::from_iter([literal!("Files Equal!")])))
    }
}

/// Error norms for `deltaSimulationResults` (C `ErrorMethod`).
enum ErrorMethod {
    Norm1,
    Norm2,
    MaxErr,
}

/// C `deltaData`: accumulate the error norm of `data` vs `refdata` sampled at
/// the reference times (with linear interpolation of the result trajectory).
fn delta_data(method: &ErrorMethod, time: &[f64], reftime: &[f64], data: &[f64], refdata: &[f64]) -> f64 {
    let mut res0 = 0.0;
    let mut i = 0usize;
    let tn = time.len();
    // C uses `0.0001*time->data[time->n]` (one past the end) as the "coincides"
    // threshold; mirror the intended "largest time" with the last element.
    let thr = (0.0001 * time[tn - 1]).max(1e-12);
    for iref in 0..reftime.len() {
        let valref = refdata[iref];
        let t = reftime[iref];
        while i < tn && time[i] < t {
            i += 1;
        }
        if i >= tn {
            break;
        }
        let i2 = i + 1;
        let val = if (time[i] - t).abs() <= thr || i2 >= tn {
            data[i]
        } else {
            (data[i2] - data[i]) / (time[i2] - time[i]) * (t - time[i]) + data[i]
        };
        match method {
            ErrorMethod::Norm1 => res0 += (valref - val).abs(),
            ErrorMethod::Norm2 => res0 += (valref - val).powi(2),
            ErrorMethod::MaxErr => res0 = (valref - val).abs().max(res0),
        }
    }
    match method {
        ErrorMethod::Norm2 => res0.sqrt(),
        _ => res0,
    }
}

pub fn deltaSimulationResults(mut filename: ArcStr, mut reffilename: ArcStr, mut method: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>) -> Result<metamodelica::Real> {
    // C: SimulationResults_deltaSimulationResults -> SimulationResultsCmp_deltaResults.
    let errmethod = match method.as_str() {
        "1norm" => ErrorMethod::Norm1,
        "2norm" => ErrorMethod::Norm2,
        "maxerr" => ErrorMethod::MaxErr,
        _ => {
            Error::addMessage(
                ErrorTypes::Message {
                    id: -1,
                    ty: ErrorTypes::MessageType::SCRIPTING,
                    severity: ErrorTypes::Severity::WARNING,
                    message: Gettext::TranslatableContent::gettext { msgid: literal!("Unknown method string: %s. 1-Norm is chosen.") },
                },
                Arc::new(List::from_iter([method.clone()])),
            )?;
            ErrorMethod::Norm1
        }
    };

    let mut reader_c = match MatReader::open(filename.as_str()) {
        Ok(r) => r,
        Err(_) => {
            err(&ERROR_OPEN_FILE, [filename.clone()])?;
            return Ok(OrderedFloat(-1.0));
        }
    };
    let mut reader_ref = match MatReader::open(reffilename.as_str()) {
        Ok(r) => r,
        Err(_) => {
            err(&ERROR_OPEN_REFFILE, [filename.clone()])?;
            return Ok(OrderedFloat(-1.0));
        }
    };

    let allvars = read_vars_filter_aliases(&reader_c);
    let allvarsref = read_vars_filter_aliases(&reader_ref);
    let mut cmpvars: Vec<ArcStr> = vars.as_ref().into_iter().cloned().collect();
    if cmpvars.is_empty() {
        cmpvars = allvarsref.clone();
        if cmpvars.is_empty() {
            err(&ERROR_GET_VARS, [])?;
            return Ok(OrderedFloat(-1.0));
        }
    }

    let time_name = get_time_var_name(&allvars);
    let timeref_name = get_time_var_name(&allvarsref);
    let time = match get_data(&mut reader_c, time_name) {
        Some(t) if !t.is_empty() => t,
        _ => {
            err(&ERROR_GET_TIME, [])?;
            return Ok(OrderedFloat(-1.0));
        }
    };
    let timeref = match get_data(&mut reader_ref, timeref_name) {
        Some(t) if !t.is_empty() => t,
        _ => {
            err(&ERROR_GET_TIME_REF, [])?;
            return Ok(OrderedFloat(-1.0));
        }
    };
    if time[0] > timeref[0] {
        err(&ERROR_FILE_STARTS_BEFORE, [])?;
        return Ok(OrderedFloat(-1.0));
    }
    if *time.last().unwrap() < *timeref.last().unwrap() {
        err(&ERROR_FILE_ENDS_BEFORE, [])?;
        return Ok(OrderedFloat(-1.0));
    }

    let offset = leading_dup_count(&time);
    let offset_ref = leading_dup_count(&timeref);
    let mut res = 0.0;
    for var in &cmpvars {
        let var1 = strip_quotes(var.as_str());
        let mut dataref = match get_data(&mut reader_ref, var1.as_str()) {
            Some(d) if !d.is_empty() => d,
            _ => continue,
        };
        let mut data = match get_data(&mut reader_c, var1.as_str()) {
            Some(d) if !d.is_empty() => d,
            _ => continue,
        };
        for j in (1..=offset).rev() {
            data[j - 1] = data[j];
        }
        for j in (1..=offset_ref).rev() {
            dataref[j - 1] = dataref[j];
        }
        res += delta_data(&errmethod, &time, &timeref, &data, &dataref);
    }
    Ok(OrderedFloat(res))
}

pub fn diffSimulationResults(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut prefix: ArcStr, mut refTol: metamodelica::Real, mut relTolDiffMaxMin: metamodelica::Real, mut rangeDelta: metamodelica::Real, mut vars: Arc<metamodelica::List<ArcStr>>, mut keepEqualResults: bool) -> Result<(bool, Arc<metamodelica::List<ArcStr>>)> {
    // C: SimulationResults_diffSimulationResults (SimulationResultsCmpTubes.c).
    todo!("SimulationResults.diffSimulationResults: result comparison not yet ported")
}

pub fn diffSimulationResultsHtml(mut runningTestsuite: bool, mut filename: ArcStr, mut reffilename: ArcStr, mut refTol: metamodelica::Real, mut relTolDiffMaxMin: metamodelica::Real, mut rangeDelta: metamodelica::Real, mut var: ArcStr) -> Result<ArcStr> {
    // C: SimulationResults_diffSimulationResultsHtml (SimulationResultsCmpTubes.c).
    todo!("SimulationResults.diffSimulationResultsHtml: result comparison not yet ported")
}

pub fn filterSimulationResults(mut inFile: ArcStr, mut outFile: ArcStr, mut vars: Arc<metamodelica::List<ArcStr>>, mut numberOfIntervals: i32, mut removeDescription: bool, mut hintReadAllVars: bool) -> Result<bool> {
    // C: SimulationResults_filterSimulationResults — copy a result file
    // keeping only the requested variables / intervals.
    todo!("SimulationResults.filterSimulationResults: result filtering not yet ported")
}
