//! `#[derive(ReferenceEq)]` — shallow observational identity for the
//! MetaModelica value types generated by mmtorust.
//!
//! MMC boxes every record and its `referenceEq` is total pointer identity.
//! The Rust port unboxes non-recursive records/uniontypes, so true pointer
//! identity does not exist for them; the strongest identity an unboxed,
//! immutable value can have is *pairwise-identical fields* (each compared
//! with `ReferenceEq` again, bottoming out at pointer identity for `Arc`/
//! `Rc` handles and value identity for scalars). Two values that agree
//! under this relation are indistinguishable from "the same object" to any
//! MetaModelica code, which is exactly the property the MM reuse/cache
//! idioms (`if referenceEq(new, old) then old else new`) rely on. See
//! `try_emit_reference_eq` in mmtorust/src/codegen.rs for the concrete-type
//! lowering this derive mirrors, and `metamodelica::ReferenceEq` for the
//! base impls.
//!
//! The expansion bounds every type parameter with
//! `metamodelica::ReferenceEq` (like `derive(Clone)` bounds `Clone`); every
//! MM-representable type implements the trait, so the bound never locks a
//! type out.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields, Index};

#[proc_macro_derive(ReferenceEq)]
pub fn derive_reference_eq(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;

    // Add `metamodelica::ReferenceEq` to every type parameter, mirroring how
    // builtin derives bound their own trait.
    let mut generics = input.generics.clone();
    for param in generics.type_params_mut() {
        param
            .bounds
            .push(syn::parse_quote!(metamodelica::ReferenceEq));
    }
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();

    let body = match &input.data {
        Data::Struct(data) => {
            let cmp = fields_cmp(&data.fields, quote!(self), quote!(other));
            quote! { #cmp }
        }
        Data::Enum(data) => {
            let arms = data.variants.iter().map(|v| {
                let vname = &v.ident;
                match &v.fields {
                    Fields::Unit => quote! {
                        (Self::#vname, Self::#vname) => true,
                    },
                    Fields::Named(named) => {
                        let names: Vec<_> = named
                            .named
                            .iter()
                            .map(|f| f.ident.as_ref().unwrap())
                            .collect();
                        let lhs: Vec<_> = names
                            .iter()
                            .map(|n| quote::format_ident!("__refeq_l_{}", n))
                            .collect();
                        let rhs: Vec<_> = names
                            .iter()
                            .map(|n| quote::format_ident!("__refeq_r_{}", n))
                            .collect();
                        quote! {
                            (Self::#vname { #(#names: #lhs),* }, Self::#vname { #(#names: #rhs),* }) =>
                                true #(&& metamodelica::ReferenceEq::reference_eq(#lhs, #rhs))*,
                        }
                    }
                    Fields::Unnamed(unnamed) => {
                        let lhs: Vec<_> = (0..unnamed.unnamed.len())
                            .map(|i| quote::format_ident!("__refeq_l{}", i))
                            .collect();
                        let rhs: Vec<_> = (0..unnamed.unnamed.len())
                            .map(|i| quote::format_ident!("__refeq_r{}", i))
                            .collect();
                        quote! {
                            (Self::#vname(#(#lhs),*), Self::#vname(#(#rhs),*)) =>
                                true #(&& metamodelica::ReferenceEq::reference_eq(#lhs, #rhs))*,
                        }
                    }
                }
            });
            // The catch-all arm is unreachable for single-variant enums, but
            // emitting it unconditionally keeps the expansion simple; allow
            // the lint instead of special-casing.
            quote! {
                #[allow(unreachable_patterns)]
                match (self, other) {
                    #(#arms)*
                    _ => false,
                }
            }
        }
        Data::Union(_) => {
            return syn::Error::new_spanned(name, "ReferenceEq cannot be derived for unions")
                .to_compile_error()
                .into();
        }
    };

    let expanded = quote! {
        impl #impl_generics metamodelica::ReferenceEq for #name #ty_generics #where_clause {
            fn reference_eq(&self, other: &Self) -> bool {
                #body
            }
        }
    };
    TokenStream::from(expanded)
}

/// Conjunction of `ReferenceEq::reference_eq` over all fields of a struct.
fn fields_cmp(
    fields: &Fields,
    lhs: proc_macro2::TokenStream,
    rhs: proc_macro2::TokenStream,
) -> proc_macro2::TokenStream {
    match fields {
        Fields::Unit => quote! { true },
        Fields::Named(named) => {
            let cmps = named.named.iter().map(|f| {
                let n = f.ident.as_ref().unwrap();
                quote! { metamodelica::ReferenceEq::reference_eq(&#lhs.#n, &#rhs.#n) }
            });
            quote! { true #(&& #cmps)* }
        }
        Fields::Unnamed(unnamed) => {
            let cmps = (0..unnamed.unnamed.len()).map(|i| {
                let idx = Index::from(i);
                quote! { metamodelica::ReferenceEq::reference_eq(&#lhs.#idx, &#rhs.#idx) }
            });
            quote! { true #(&& #cmps)* }
        }
    }
}
