// Hand-maintained: NOT generated by mmtorust.
//
// Rust port of `OMCompiler/Compiler/Util/Autoconf.mo`. Upstream, that file
// is produced at *configure time* by substituting platform facts into
// `Autoconf.mo.in` (Unix) or `Autoconf.mo.omdev.mingw` (Windows/OMDev).
// The Rust port runs no configure step, so this module is hand-written and
// detects the platform with Rust's compile-time `cfg!` instead; `Autoconf`
// is listed in `HANDWRITTEN_TOP_PACKAGES` (mmtorust/src/codegen.rs) to skip
// its codegen.
//
// Values mirror what the two upstream templates produce on each platform:
//
//   * Linux   — the values configure substitutes on a GNU/Linux host
//     (the same ones the previously generated file carried).
//   * Windows — `Autoconf.mo.omdev.mingw` with a current OMDev
//     (`isNewOMDev` / `isNewNewOMDev` both true), i.e. a MinGW
//     toolchain. The link-flag soup is kept verbatim from that file.
//   * macOS   — best-effort: configure substitutes `.dylib` / no
//     `-Wl,-Bstatic`; the ldflags mirror the Linux set minus the
//     GNU-ld-only options. Untested — verify against a configured
//     `Autoconf.mo` before relying on a macOS build.
//
// The constants must stay `const` (not `static`): generated code embeds
// them with `arcstr::literal!(Autoconf::xxx)` and in `const_str::equal!`
// comparisons, both of which require const expressions.

/*
 * This file is part of OpenModelica.
 *
 * Copyright (c) 1998-2026, Open Source Modelica Consortium (OSMC),
 * c/o Linköpings universitet, Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF AGPL VERSION 3 LICENSE OR
 * THIS OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.8.
 * ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
 * RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GNU AGPL
 * VERSION 3, ACCORDING TO RECIPIENTS CHOICE.
 *
 * See the full OSMC Public License conditions for more details.
 *
 */
#![allow(non_upper_case_globals, non_snake_case, dead_code)]

use std::sync::Arc;

use arcstr::{literal, ArcStr};
use metamodelica::list;

pub const configureCommandLine: &'static str =
    "Hand-maintained Autoconf.rs (Rust port); platform detected at compile time, no configure run";

/// `@CONFIG_OS@`: "Windows_NT" on Windows, "darwin" on macOS, otherwise
/// `$host_os` with the `-gnu` suffix stripped (i.e. "linux").
pub const os: &'static str = if cfg!(windows) {
    "Windows_NT"
} else if cfg!(target_os = "macos") {
    "darwin"
} else {
    "linux"
};

pub const is64Bit: bool = cfg!(target_pointer_width = "64");

pub const isWindows: bool = cfg!(windows);

pub const platform: &'static str = if isWindows && is64Bit {
    "WIN64"
} else if isWindows {
    "WIN32"
} else {
    "Unix"
};

// On Windows shells, commands go through `cmd /c`, so the MSYS `make` must
// not be used — `Autoconf.mo.omdev.mingw` mandates `mingw32-make` there.
pub const make: &'static str = if isWindows { "mingw32-make" } else { "make" };

pub const cmake: &'static str = "cmake";

pub const exeExt: &'static str = if isWindows { ".exe" } else { "" };

/// `@SHREXT@`.
pub const dllExt: &'static str = if isWindows {
    ".dll"
} else if cfg!(target_os = "macos") {
    ".dylib"
} else {
    ".so"
};

/// `@BSTATIC@`: whether the linker understands `-Wl,-Bstatic` (GNU ld /
/// MinGW yes, Apple's ld64 no).
pub const haveBStatic: bool = !cfg!(target_os = "macos");

pub const bstatic: &'static str = if haveBStatic { "-Wl,-Bstatic" } else { "" };

pub const bdynamic: &'static str = if haveBStatic { "-Wl,-Bdynamic" } else { "" };

pub const groupDelimiter: &'static str = if isWindows { ";" } else { ":" };

pub const pathDelimiter: &'static str = "/";

// ── Link flags for generated simulation / FMU code ──────────────────────────
//
// Windows: composed exactly like `Autoconf.mo.omdev.mingw` with
// `isNewOMDev`/`isNewNewOMDev` = true (current OMDev: no gfortranbegin/
// msvcrt, -lz/-lsz instead of -lzip/-lszip). `OMC_LDFLAGS_LINK_TYPE` is a
// variable in the generated Makefile, substituted by make itself.
// Unix: the values configure produces on GNU/Linux; macOS drops the
// GNU-ld-only flags (see the module comment).

const win_linkType: &'static str = " -Wl,-B$(OMC_LDFLAGS_LINK_TYPE) ";

const win_ldflags_basic: &'static str = const_str::concat!(
    " -lomcgc -lryu ",
    win_linkType,
    "-static-libgcc -luuid -loleaut32 -lole32 -limagehlp -lws2_32",
    " -lpthread -lm ",
    "-lgfortran -lquadmath -lmingw32 -lgcc_eh -lmoldname -lmingwex ",
    "-luser32 -lkernel32 -ladvapi32 -lshell32 -lopenblas -Wl,-Bdynamic"
);

const win_ldflags_zip: &'static str = "-lz -lsz ";

const win_ldflags_runtime_fmu: &'static str = const_str::concat!(
    win_linkType,
    "-lregex -ltre -lintl -liconv -static-libgcc -lpthread -lm ",
    "-lgfortran -lquadmath -lmingw32 -lgcc_eh -lmoldname -lmingwex ",
    "-luser32 -lkernel32 -ladvapi32 -lshell32 -limagehlp -lopenblas -lhdf5 ",
    win_ldflags_zip,
    "-Wl,-Bdynamic"
);

/// `@RT_LDFLAGS_GENERATED_CODE@`.
pub const ldflags_runtime: &'static str = if cfg!(windows) {
    const_str::concat!(" -lOpenModelicaRuntimeC", win_ldflags_basic)
} else if cfg!(target_os = "macos") {
    " -lOpenModelicaRuntimeC -lopenblas -lm -lomcgc -lryu -lpthread"
} else {
    " -Wl,--no-as-needed -Wl,--disable-new-dtags -lOpenModelicaRuntimeC -lopenblas -lm -lomcgc -lryu -lpthread -rdynamic"
};

/// `@RT_LDFLAGS_GENERATED_CODE_SIM@`.
pub const ldflags_runtime_sim: &'static str = if cfg!(windows) {
    const_str::concat!(
        "-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lryu -lopenblas",
        win_linkType,
        " -lstdc++ -Wl,-Bdynamic "
    )
} else if cfg!(target_os = "macos") {
    " -lSimulationRuntimeC -lopenblas -lm -lomcgc -lryu -lpthread"
} else {
    " -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -lopenblas -lm -lomcgc -lryu -lpthread -rdynamic -Wl,--no-undefined"
};

/// `@RT_LDFLAGS_GENERATED_CODE_SOURCE_FMU@`.
pub const ldflags_runtime_fmu: &'static str = if cfg!(windows) {
    win_ldflags_runtime_fmu
} else if cfg!(target_os = "macos") {
    " -lopenblas -lm -lpthread -lryu"
} else {
    " -Wl,--no-as-needed -Wl,--disable-new-dtags -lopenblas -lm -lpthread -lryu -rdynamic  -Wl,--no-undefined"
};

/// `@RT_LDFLAGS_GENERATED_CODE_SOURCE_FMU_STATIC@`.
pub const ldflags_runtime_fmu_static: &'static str = if cfg!(windows) {
    const_str::concat!(" -lSimulationRuntimeFMI ", win_ldflags_runtime_fmu)
} else if cfg!(target_os = "macos") {
    " -lSimulationRuntimeFMI -lopenblas -lm -lpthread -lryu"
} else {
    " -Wl,-Bstatic -lSimulationRuntimeFMI  -Wl,--no-as-needed -Wl,--disable-new-dtags -lopenblas -Wl,-Bdynamic -lryu -lm -lpthread -rdynamic  -Wl,--no-undefined"
};

/// Libraries linked into generated simulation code when --parmodauto
/// (ParModelica auto) is enabled. Mirrors `Util/Autoconf.mo`, which hardcodes
/// the pair below: the ParModelica auto runtime (`libParModelicaAuto`) ships
/// with the OpenModelica build on every supported platform.
pub const parModelicaAutoLibs: &'static str = " -lParModelicaAuto -ltbb ";

pub const corbaLibs: &'static str = "";

/// `@WITH_HWLOC@` defaults to 0 on every platform unless explicitly
/// requested at configure time; mirror the default.
pub const hwloc: &'static str = "";

pub static systemLibs: std::sync::LazyLock<Arc<metamodelica::List<ArcStr>>> =
    std::sync::LazyLock::new(|| {
        if isWindows {
            // Autoconf.mo.omdev.mingw: constant list<String> systemLibs = {};
            metamodelica::nil()
        } else {
            list![
                literal!("-lomcruntime"),
                literal!("-lexpat"),
                literal!("-lsqlite3"),
                arcstr::literal!(corbaLibs),
                literal!("-lomcgc"),
                arcstr::literal!(hwloc)
            ]
        }
    });

/// `$host_cpu` for the compilation target. Extend the chain when porting to
/// a new architecture — an explicit "unknown" keeps path construction
/// greppable rather than silently wrong.
const target_arch_str: &'static str = if cfg!(target_arch = "x86_64") {
    "x86_64"
} else if cfg!(target_arch = "aarch64") {
    "aarch64"
} else if cfg!(target_arch = "x86") {
    "i686"
} else if cfg!(target_arch = "arm") {
    "arm"
} else if cfg!(target_arch = "riscv64") {
    "riscv64"
} else {
    "unknown"
};

/// `-$host_os` for the compilation target (Unix only; Windows uses "").
const os_triple_suffix: &'static str = if cfg!(target_os = "macos") {
    "-apple-darwin"
} else if cfg!(all(target_os = "linux", target_env = "musl")) {
    "-linux-musl"
} else {
    "-linux-gnu"
};

/// `@host_short@` = `$host_cpu-$host_os`: the multiarch-style directory
/// component under `lib/` where the omc runtime libraries are installed
/// (e.g. `/usr/lib/x86_64-linux-gnu/omc`). The OMDev Windows file uses the
/// empty string (no per-triple subdirectory on Windows installs).
pub const triple: &'static str = if cfg!(windows) {
    ""
} else {
    const_str::concat!(target_arch_str, os_triple_suffix)
};
