[package]
name = "mmwinnow"
version = "0.1.0"
edition = "2024"

[dependencies]
arcstr.workspace = true
metamodelica.workspace = true
anyhow.workspace = true
list_comprehension_macro.workspace = true
rayon.workspace = true
winnow.workspace = true

[dev-dependencies]
backtrace-on-stack-overflow = "0.3.0"
winnow = "0.7"
