[package]
name = "mmwinnow"
version = "0.1.0"
edition = "2024"

#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-Clink-arg=-Wl,--no-rosegment"]

[dependencies]
anyhow = "1.0.102"
list_comprehension_macro = "0.1.1"
rayon = "1"
winnow = "0.7"

[dev-dependencies]
backtrace-on-stack-overflow = "0.3.0"
winnow = "0.7"
